import { getDayNumber } from "./gameUtils";

export interface SpellingBeePuzzle {
  date: string;
  centerLetter: string;
  outerLetters: [string, string, string, string, string, string];
  pangrams: string[];
  validWords: string[];
}

export const SPELLING_BEE_PUZZLES: SpellingBeePuzzle[] = [
  {
    date: "2025-05-25",
    centerLetter: "T",
    outerLetters: ["A", "N", "G", "E", "R", "S"],
    pangrams: ["GRANTEES", "GREATNESS"],
    validWords: [
      "ANTS",
      "ANTE",
      "ANTES",
      "EARN",
      "EARNS",
      "EAST",
      "EATS",
      "GATE",
      "GATES",
      "GNAT",
      "GNATS",
      "GRANT",
      "GRANTS",
      "GRANTEE",
      "GRATE",
      "GRATES",
      "GREAT",
      "GREATS",
      "NAGS",
      "NEAT",
      "NEATS",
      "NEST",
      "NETS",
      "RAGE",
      "RAGES",
      "RANG",
      "RANT",
      "RANTS",
      "RATE",
      "RATES",
      "RETE",
      "SAGE",
      "SANE",
      "SANG",
      "SATE",
      "SERA",
      "SNAG",
      "SNARE",
      "STAR",
      "STARE",
      "STAG",
      "STAGE",
      "TANG",
      "TANGS",
      "TANS",
      "TARE",
      "TARES",
      "TARN",
      "TARNS",
      "TEAS",
      "TEEN",
      "TEENS",
      "TENS",
      "TERN",
      "TERNS",
      "TREE",
      "TREES",
      "GRANTEES",
      "GREATNESS",
    ],
  },
  {
    date: "2025-05-24",
    centerLetter: "L",
    outerLetters: ["A", "P", "E", "C", "O", "R"],
    pangrams: ["CORPORAL"],
    validWords: [
      "ACRE",
      "ACRES",
      "ORCA",
      "ORAL",
      "ROLE",
      "POLE",
      "PACE",
      "PALER",
      "PEARL",
      "PLACE",
      "POLAR",
      "POLCA",
      "RECLAP",
      "CORAL",
      "CORPOREAL",
      "CORPORAL",
      "LACE",
      "LACES",
      "LACER",
      "LORE",
      "LOPER",
      "PARCEL",
      "PAROL",
      "PAROLE",
      "PEAL",
      "PEALS",
      "PORE",
      "PORES",
      "REAL",
      "REAP",
      "REPO",
      "REPRO",
      "ROPE",
      "ROPES",
      "OPAL",
      "OPERA",
      "OPALE",
    ],
  },
  {
    date: "2025-05-23",
    centerLetter: "I",
    outerLetters: ["M", "P", "A", "R", "T", "S"],
    pangrams: ["IMPARTS", "PARTISAM"],
    validWords: [
      "AIMS",
      "AIRS",
      "AMIR",
      "AMIS",
      "ARIA",
      "ARIAS",
      "ARMS",
      "ATRIA",
      "IMPART",
      "IMPARTS",
      "IMPAIRS",
      "MARS",
      "MAST",
      "MATS",
      "MATES",
      "MIRA",
      "MIST",
      "PAIRS",
      "PARS",
      "PART",
      "PARTS",
      "PAST",
      "PATS",
      "PIRATE",
      "PIRATES",
      "PITS",
      "RATS",
      "RIMS",
      "RIPS",
      "SARI",
      "SITAR",
      "SLIM",
      "SLIME",
      "SPAT",
      "SPIT",
      "STAR",
      "STIR",
      "STRAP",
      "STRIP",
      "TAMS",
      "TAPS",
      "TARS",
      "TIPS",
      "TRAM",
      "TRAMPS",
      "TRAP",
      "TRIMS",
      "TRIP",
      "TRIPS",
    ],
  },
];

export function getSpellingBeePuzzle(dateStr: string): SpellingBeePuzzle {
  const found = SPELLING_BEE_PUZZLES.find((p) => p.date === dateStr);
  if (found) return found;
  const index = getDayNumber(dateStr) % SPELLING_BEE_PUZZLES.length;
  return SPELLING_BEE_PUZZLES[index];
}

export function getUniqueValidWords(puzzle: SpellingBeePuzzle): Set<string> {
  return new Set(puzzle.validWords.map((w) => w.toUpperCase()));
}
